// ---------------------------------------------------------------------------
// Meetitems voor de kennischeck bij het T4P Business Kompas.
//
// Dit bestand is GEGENEREERD. Wijzig het niet met de hand: de inhoud komt uit
// het gecontroleerde corpus en wordt door scripts/genereer-corpus-ts.py
// opnieuw weggeschreven. Een handmatige wijziging hier verdwijnt bij de
// volgende generatie en ontsnapt aan de controle die op het corpus draait.
//
// Elke bewering in een item staat in docs/ITEMBRON-T4P-KENNISCHECK.md, met het
// codepad erbij. Dat is opzet: een kennischeck die iets fout rekent wat de code
// anders doet, meet de gissing van de itemschrijver en niet de bekwaamheid van
// de kandidaat. Bij een bezwaar is zo'n item niet te verdedigen.
//
// De stam van geen enkel item valt samen met de dertig vragen van de
// tussentijdse metingen in server/routes-stm.ts. Die zijn oefenstof en zijn dus
// bij de kandidaat bekend; als meetitem zouden ze een hoge score opleveren
// zonder dat er iets gemeten is. tests/bekwaamheid-itemcorpus.test.ts houdt dat
// tegen door beide bronnen te vergelijken.
//
// Deze laag is zuiver: geen opslag, geen netwerk, geen tijd, geen toeval.
// ---------------------------------------------------------------------------

import type { ItemInvoer } from "./itembank.js";

/** Het instrument waar dit corpus bij hoort. */
export const CORPUS_INSTRUMENT = "t4p-business-kompas";

/**
 * De tachtig meetitems, tweemaal het blokplan van de kennischeck.
 *
 * Het draaiboek noemt zestig items per instrument. Onder de uitsluitingsregel
 * van de herkansing - een herkansing sluit alle items uit die deze persoon
 * eerder zag - is zestig niet genoeg voor twee volle rondes: blok A vraagt er
 * tien per afname en zou bij een evenredige verdeling over zestig items op
 * vijftien blijven steken. Tachtig maakt de tweede ronde werkelijk uitvoerbaar.
 */
export const ITEMCORPUS_T4P: readonly ItemInvoer[] = [
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke energiemodus past bij de familie Drivers wanneer de afname-instructie wordt toegepast?",
    opties: [
      "Drivers hebben energiemodus item; energie wordt alleen bij de gekozen meest en minst bevraagd.",
      "Talent-foci hebben energiemodus block.",
      "Talent-versnellers hebben energiemodus block.",
      "connection0to10 heeft bereik 0 tot 10.",
    ],
    sleutel: "A",
    toelichtingGoed: "Bij drivers is de energiemodus item: energie wordt alleen gevraagd bij de gekozen meest en minst herkenbare uitspraken.",
    toelichtingFout: "De denkfout is het verwarren van drivers met de twee talentfamilies. Daar wordt energie per blok, niet per item, bevraagd.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "juistfout",
    stam: "Bij Talent-foci wordt energie per blok bevraagd en niet per afzonderlijk item.",
    opties: null,
    sleutel: "juist",
    toelichtingGoed: "De tabel met families kent Talent-foci de energiemodus block toe. Dat onderscheidt deze familie van de drivers met modus item.",
    toelichtingFout: "De denkfout is dat energie per item bij Talent-foci zou horen. Die werkwijze is uitsluitend vastgelegd voor de familie Drivers.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke beschrijving onderbouwt dat Talent-foci en Talent-versnellers dezelfde energiemodus hebben?",
    opties: [
      "Drivers hebben vijf constructen en tien blokken.",
      "Talent-foci en Talent-versnellers hebben energiemodus block.",
      "Drivers hebben energiemodus item.",
      "De sectie connection heeft type numeric-scale en vier vragen.",
    ],
    sleutel: "B",
    toelichtingGoed: "Talent-foci en Talent-versnellers hebben beide energiemodus block. Daardoor wordt de energie bij deze twee families per blok bevraagd.",
    toelichtingFout: "De denkfout is Drivers bij een blokmodus plaatsen. Drivers hebben juist de afwijkende energiemodus item binnen het instrument.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Een gekozen uitspraak is een driver. Op welk moment hoort de energie daarbij te worden uitgevraagd?",
    opties: [
      "Talent-foci hebben energiemodus block.",
      "De sectie connection heeft vier vragen op een schaal van 0 tot 10.",
      "Bij de gekozen meest en minst herkenbare uitspraak.",
      "Main heeft 34 blokken.",
    ],
    sleutel: "C",
    toelichtingGoed: "De instructie koppelt energie bij drivers aan itemniveau, en beperkt die bevraging tot de gekozen meest en minst herkenbare uitspraken.",
    toelichtingFout: "De denkfout is een blok- of sectiemeting toepassen op een driver. De bron maakt voor drivers expliciet een itemniveau-uitzondering.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1; ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke familie omvat zes constructen en telt daardoor veertien blokken in main?",
    opties: [
      "Drivers.",
      "Talent-foci.",
      "Organisatieverbondenheid.",
      "Talent-versnellers.",
    ],
    sleutel: "D",
    toelichtingGoed: "Talent-versnellers bestaan uit zes constructen en hebben veertien blokken. Drivers en Talent-foci hebben elk vijf constructen en tien blokken.",
    toelichtingFout: "De denkfout is de families met vijf constructen of de afzonderlijke connection-sectie gelijkstellen aan de familie Talent-versnellers.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1; ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Waar hoort het construct Constructief onderscheidend in de opbouw van het T4P Business Kompas thuis?",
    opties: [
      "Bij de Talent-versnellers met energiemodus block.",
      "Be Perfect is een construct van Drivers met energiemodus item.",
      "Innovatie is een construct van Talent-foci met energiemodus block.",
      "De sectie connection heeft vier vragen.",
    ],
    sleutel: "A",
    toelichtingGoed: "Constructief onderscheidend staat in de lijst van Talent-versnellers. Voor die familie is de energiemodus block vastgelegd.",
    toelichtingFout: "De denkfout is dit construct onder Drivers, Talent-foci of connection plaatsen. De bron classificeert het uitsluitend als Talent-versneller.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "juistfout",
    stam: "Hurry Up en Faciliteren zijn beide constructen binnen de familie Drivers.",
    opties: null,
    sleutel: "onjuist",
    toelichtingGoed: "Dit is onjuist. Hurry Up is een driver, maar Faciliteren hoort bij de talent-versnellers. De vijf drivers zijn Be Perfect, Be Strong, Hurry Up, Please Others en Try Hard.",
    toelichtingFout: "De denkfout is aannemen dat een werkwoordachtige naam een driver aanduidt. De familie is niet aan de vorm van de naam te zien; ze volgt uit de indeling van het instrument, en die bepaalt ook of energie per item of per blok wordt bevraagd.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke combinatie beschrijft het structurele verschil tussen Talent-foci en Talent-versnellers correct?",
    opties: [
      "Drivers hebben vijf constructen en tien blokken met energiemodus item.",
      "Talent-foci hebben vijf constructen en tien blokken; Talent-versnellers zes constructen en veertien blokken.",
      "Talent-foci hebben energiemodus block.",
      "Talent-versnellers hebben energiemodus block.",
    ],
    sleutel: "B",
    toelichtingGoed: "De twee talentfamilies delen de blokgebonden energiemodus, maar verschillen in omvang: vijf constructen en tien blokken tegenover zes en veertien.",
    toelichtingFout: "De denkfout is hun aantallen omdraaien of Talent-foci een itemmodus geven. De bron reserveert itemenergie uitsluitend voor Drivers.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke beschrijving houdt de sectie main en de sectie connection inhoudelijk uit elkaar?",
    opties: [
      "Main heeft 34 blokken en 136 items.",
      "Connection heeft vier vragen op een schaal van 0 tot 10.",
      "Main is forced-choice-with-energy; connection is numeric-scale met vier vragen.",
      "Talent-versnellers hebben veertien blokken.",
    ],
    sleutel: "C",
    toelichtingGoed: "Main heeft het type forced-choice-with-energy. Connection is een afzonderlijke numeric-scale-sectie met vier vragen over organisatieverbondenheid.",
    toelichtingFout: "De denkfout is de twee sectietypen verwisselen of ze als identiek behandelen. De bron legt voor main en connection verschillende typen vast.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke technische koppeling hoort bij de vier vragen over organisatieverbondenheid?",
    opties: [
      "Energie per item bij de gekozen meest en minst.",
      "Energiewaarden van −2 tot +2.",
      "Veertien blokken in main.",
      "linkKey: respondentCode.",
    ],
    sleutel: "D",
    toelichtingGoed: "De vier connection-vragen zijn gekoppeld via linkKey: respondentCode. Dit staat bij de sectie organisatieverbondenheid vermeld.",
    toelichtingFout: "De denkfout is een kenmerk van energiemeting of van main als koppeling voor connection-vragen gebruiken. De bron noemt hiervoor respondentCode.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke vraag hoort als q3 bij de sectie organisatieverbondenheid van het instrument?",
    opties: [
      "Zelfinvestering.",
      "Psychologische verbondenheid.",
      "Billijkheid / verloning.",
      "Organisatie-investering.",
    ],
    sleutel: "A",
    toelichtingGoed: "In de tabel van de connection-sectie is q3 gekoppeld aan Zelfinvestering. De overige labels horen bij q1, q2 en q4.",
    toelichtingFout: "De denkfout is de vier labels niet aan hun eigen vraag-id koppelen. De bron geeft voor ieder van q1 tot en met q4 een afzonderlijke koppeling.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "juistfout",
    stam: "De schaal energy en de schaal baselineEnergy0to10 hebben hetzelfde bereik.",
    opties: null,
    sleutel: "onjuist",
    toelichtingGoed: "Dit is onjuist. De schaal energy loopt van −2 tot +2, terwijl baselineEnergy0to10 van 0 tot 10 loopt. Juist daarom is er een herschaling nodig voordat de twee met elkaar vergeleken kunnen worden.",
    toelichtingFout: "De denkfout is de twee energiematen als één schaal behandelen omdat ze beide over energie gaan. Wie ze verwisselt, telt een waarde van −2 en een waarde van 0 als hetzelfde, terwijl −2 na herschaling juist de ondergrens 0 oplevert.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke schaalbeschrijving past bij een antwoord dat het label Neutraal draagt?",
    opties: [
      "connection0to10, met bereik 0 tot 10.",
      "energy, met waarde 0 op een ordinale schaal van −2 tot +2.",
      "baselineEnergy0to10, met bereik 0 tot 10.",
      "energy, met bovengrens +2.",
    ],
    sleutel: "B",
    toelichtingGoed: "De labels van energy kennen de waarde 0 toe aan Neutraal. Deze schaal loopt ordinaal van −2 tot en met +2.",
    toelichtingFout: "De denkfout is het neutrale energielabel op een 0-tot-10-schaal of op een andere waarde plaatsen. De bron specificeert hiervoor energy = 0.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke energielabels horen bij de twee negatieve waarden van de schaal energy?",
    opties: [
      "0: Neutraal.",
      "+1: Geeft eerder energie.",
      "−2: Kost veel energie; −1: Kost eerder energie.",
      "+2: bovengrens.",
    ],
    sleutel: "C",
    toelichtingGoed: "De antwoordschalen koppelen −2 aan Kost veel energie en −1 aan Kost eerder energie. Neutraal hoort bij 0.",
    toelichtingFout: "De denkfout is labels van 0 of van positieve energie aan negatieve schaalwaarden koppelen. De bron onderscheidt deze waarden uitdrukkelijk.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke omvang hoort bij de sectie main, los van de vier vragen in connection?",
    opties: [
      "Drivers hebben tien blokken.",
      "Talent-versnellers hebben veertien blokken.",
      "Connection heeft vier vragen.",
      "34 blokken en 136 items.",
    ],
    sleutel: "D",
    toelichtingGoed: "De instrumenttabel vermeldt voor main 34 blokken en 136 items. Connection is daarvan apart opgevoerd als numeric-scale met vier vragen.",
    toelichtingFout: "De denkfout is aantallen van één familie of de connection-sectie gebruiken als totale omvang van main. De bron noemt daarvoor 34 en 136.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke omschrijving van de exploratieve factoranalyse is volgens de onderzoeksinformatie correct?",
    opties: [
      "De analyse omvatte 1.858 T4Professional-profielen en 395 profielen van het sportinstrument.",
      "De externe inhoudsvalidatie gebeurde door vier onafhankelijke experts.",
      "De statistische vormgeving is nagekeken door sectorfonds IVOC.",
      "De bevindingen van de inhoudsvalidatie zijn niet als afzonderlijk rapport gepubliceerd.",
    ],
    sleutel: "A",
    toelichtingGoed: "De exploratieve factoranalyse wordt gekoppeld aan twee profielgroepen: 1.858 T4Professional-profielen en 395 profielen van het sportinstrument.",
    toelichtingFout: "De denkfout is een ander onderzoekselement als omschrijving van de factoranalyse kiezen. De andere uitspraken betreffen inhoudsvalidatie of statistische vormgeving.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke factorladingen worden in de onderzoeksinformatie aan de driverschalen toegeschreven?",
    opties: [
      "0,63–0,84 voor energieschalen onder de talentversnellers.",
      "0,90–0,97.",
      "1.858 T4Professional-profielen en 395 profielen van het sportinstrument.",
      "Vier onafhankelijke experts voor externe inhoudsvalidatie.",
    ],
    sleutel: "B",
    toelichtingGoed: "De bron vermeldt factorladingen van 0,90–0,97 voor de driverschalen. De range 0,63–0,84 betreft energieschalen onder de talentversnellers.",
    toelichtingFout: "De denkfout is een andere gerapporteerde range of een deelnemersaantal als factorlading voor drivers gebruiken. De driverschalen hebben hun eigen range.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke reeks bevat uitsluitend constructen uit de familie Talent-foci van het T4P Business Kompas?",
    opties: [
      "Analyse, Coaching, Faciliteren, Impact, Resultaatgericht.",
      "Be Perfect, Be Strong, Hurry Up, Please Others, Try Hard.",
      "Innovatie, Inter-relationeel, Operationeel, Strategie, TaPas-Beeld.",
      "Innovatie, Strategie, Impact, Analyse, TaPas-Beeld.",
    ],
    sleutel: "C",
    toelichtingGoed: "De familie Talent-foci bestaat uit vijf constructen: Innovatie, Inter-relationeel, Operationeel, Strategie en TaPas-Beeld. Ze worden bevraagd met energie op blokniveau.",
    toelichtingFout: "De denkfout is de drie families door elkaar halen. Analyse, Coaching, Faciliteren, Impact en Resultaatgericht zijn talent-versnellers; Be Perfect en de andere vier zijn drivers. Een reeks die foci en versnellers mengt, zoals Innovatie samen met Impact en Analyse, hoort bij geen van de families.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §1.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "juistfout",
    stam: "Het extractiemodel, de fit-indices en de volledige factormatrix zijn niet gepubliceerd.",
    opties: null,
    sleutel: "juist",
    toelichtingGoed: "De onderzoeksbeschrijving vermeldt expliciet dat het extractiemodel, de fit-indices en de volledige factormatrix niet zijn gepubliceerd.",
    toelichtingFout: "De denkfout is uit de aanwezigheid van een exploratieve analyse afleiden dat alle technische uitwerkingen extern beschikbaar zijn. Dat staat niet in de bron.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "A",
    soort: "meerkeuze",
    stam: "Welke omschrijving past bij de externe inhoudsvalidatie die in de onderzoeksinformatie wordt genoemd?",
    opties: [
      "Een exploratieve factoranalyse met de Universiteit Antwerpen en prof. dr. Guido Van Hal en prof. dr. Stefan Van Dongen.",
      "Factorladingen van 0,90–0,97 voor driverschalen en 0,63–0,84 voor energieschalen onder talentversnellers.",
      "Statistische vormgeving nagekeken door sectorfonds IVOC.",
      "Vier onafhankelijke experts, twee Vlaamse en twee Nederlandse, onder supervisie van prof. dr. Peter Theuns van de VUB.",
    ],
    sleutel: "D",
    toelichtingGoed: "De externe inhoudsvalidatie is beschreven als werk van vier onafhankelijke experts, onder supervisie van prof. dr. Peter Theuns van de VUB.",
    toelichtingFout: "De denkfout is factoranalyse, factorladingen of de IVOC-controle verwarren met externe inhoudsvalidatie. De bron benoemt deze als afzonderlijke onderzoekselementen.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Een construct is 3 keer als meest en 1 keer als minst herkenbaar gekozen. Welke netscore volgt uit de constructberekening?",
    opties: [
      "−2",
      "2",
      "3",
      "4",
    ],
    sleutel: "B",
    toelichtingGoed: "De netscore is most − least. Bij 3 keer most en 1 keer least is de uitkomst dus 3 − 1 = 2.",
    toelichtingFout: "De denkfout is most en least optellen of één van beide tellingen overnemen. Net is uitsluitend het verschil most − least.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Voor een construct zijn geen energiewaarden verzameld. Welke duiding van avgEnergy is dan volgens de scoring correct?",
    opties: [
      "avgEnergy is 0; hetzelfde getal kan ook ontstaan bij een neutraal gemeten energie.",
      "avgEnergy ontbreekt en krijgt geen getalswaarde.",
      "avgEnergy wordt automatisch 5 op de tienschaal.",
      "avgEnergy wordt gelijkgesteld aan de netscore van het construct.",
    ],
    sleutel: "A",
    toelichtingGoed: "Bij geen energiewaarden is avgEnergy 0. Omdat 0 op de itemschaal ook Neutraal betekent, is het onderscheid in dit veld niet zichtbaar.",
    toelichtingFout: "De denkfout is 0 altijd als een werkelijk neutrale meting lezen. De terugval bij ontbrekende energiewaarden levert exact dezelfde waarde 0 op.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Welke drivers worden als uitgangspunt gebruikt voordat de gemiddelde energie voor driverRisk wordt bepaald?",
    opties: [
      "De twee drivers met de hoogste avgEnergy.",
      "De top 2 drivers na sortering op net, aflopend.",
      "De top 3 drivers na sortering op net, aflopend.",
      "Alle drivers met een avgEnergy lager dan 0.",
    ],
    sleutel: "B",
    toelichtingGoed: "DriverRisk sorteert de drivers eerst op net in aflopende volgorde en neemt vervolgens de top 2. Pas van die twee wordt avg berekend.",
    toelichtingFout: "De denkfout is selectie op energiewaarde of op drie drivers veronderstellen. De selectie gebeurt uitsluitend op net, aflopend, en omvat precies twee drivers.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "De gemiddelde avgEnergy van de twee geselecteerde topdrivers is precies 0. Welk driverRisk-label hoort daarbij?",
    opties: [
      "hoog",
      "matig",
      "laag",
      "Er wordt geen label toegekend.",
    ],
    sleutel: "C",
    toelichtingGoed: "Bij avg === 0 of hoger kent driverRisk het label laag toe. Matig geldt alleen bij avg kleiner dan 0 én groter dan −1.",
    toelichtingFout: "De denkfout is 0 onder de categorie matig laten vallen. De grens voor matig sluit 0 uit; daardoor valt precies 0 onder laag.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "De berekende consistentiescore is precies 80. Welk consistentielabel kent de rapportlogica dan toe?",
    opties: [
      "laag",
      "middelmatig",
      "Er is eerst een aanvullende afronding nodig.",
      "hoog",
    ],
    sleutel: "D",
    toelichtingGoed: "Het label hoog geldt bij score >= 80. Een score die precies 80 is, voldoet dus direct aan de voorwaarde voor hoog.",
    toelichtingFout: "De denkfout is de grens te lezen als strikt hoger dan 80. In de regel staat >= 80, waardoor 80 zelf al hoog is.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Twee afnames verschillen alleen in energySpread: de ene heeft 2 en de andere 7. Welke afname krijgt de hogere spreadPart?",
    opties: [
      "De afname met energySpread 2.",
      "De afname met energySpread 7.",
      "Beide afnames krijgen altijd spreadPart 10.",
      "De spreadPart wordt niet door energySpread beïnvloed.",
    ],
    sleutel: "A",
    toelichtingGoed: "SpreadPart is max(0, 10 − min(10, energySpread)). Een kleinere energySpread geeft daarom een hogere spreadPart dan een grotere spreiding.",
    toelichtingFout: "De denkfout is een grotere spreiding als een hogere deelscore beschouwen. De formule trekt energySpread juist af, waardoor 7 lager uitkomt dan 2.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Een respondent heeft 13 ingevulde blokken. Wat is dan totalChoices in buildMainScores?",
    opties: [
      "13",
      "26",
      "34",
      "39",
    ],
    sleutel: "D",
    toelichtingGoed: "BuildMainScores berekent totalChoices als completedScreens * 3. Bij 13 ingevulde blokken is dat 13 * 3, dus 39.",
    toelichtingFout: "De denkfout is completedScreens zelf, het totale aantal van 34, of een verdubbeling gebruiken. De vastgelegde berekening vermenigvuldigt completedScreens met 3.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.4",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "De baseline is 8 en normalizedQuestionnaireEnergy is 6. Welke energyDiscrepancy volgt volgens buildMainScores?",
    opties: [
      "−2",
      "0",
      "2",
      "14",
    ],
    sleutel: "C",
    toelichtingGoed: "EnergyDiscrepancy is baseline − normalized. Met baseline 8 en normalized 6 is de discrepantie dus 8 − 6 = 2.",
    toelichtingFout: "De denkfout is de aftrekvolgorde omkeren of de twee waarden optellen. De formule schrijft baseline min normalized voor, niet andersom.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.4",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Welke waarde op de tienschaal geeft energieNaarTienschaal voor een gemiddelde energiewaarde van 0?",
    opties: [
      "0",
      "3",
      "5",
      "10",
    ],
    sleutel: "C",
    toelichtingGoed: "De herschaling van −2..+2 naar 0..10 legt expliciet vast dat 0 wordt omgezet naar 5, afgerond op twee decimalen.",
    toelichtingFout: "De denkfout is 0 op de oorspronkelijke energieschaal verwarren met 0 op de tienschaal. De vastgelegde herschaling zet 0 juist op 5.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.5",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Een waarde op de tienschaal is precies 7,5. Welke energieband geldt volgens de vastgelegde bandgrenzen?",
    opties: [
      "wisselend",
      "hoog",
      "stevig",
      "kwetsbaar",
    ],
    sleutel: "B",
    toelichtingGoed: "De band hoog begint vanaf 7,5. Een waarde die precies 7,5 is, valt daarom in de band hoog.",
    toelichtingFout: "De denkfout is de grens 7,5 uitsluiten of de lagere band kiezen. Het woord vanaf maakt duidelijk dat 7,5 zelf al hoog is.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.5",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Er zijn 4 items met tijdgegevens in een afname. Wat gebeurt er volgens de afnamekwaliteitslogica met een eventuele vlag?",
    opties: [
      "De vlag wordt altijd gezet zodra het aandeel 0,15 is.",
      "De vlag wordt alleen gezet bij een score lager dan 60.",
      "De vlag wordt nooit gezet, ook al wordt het aandeel berekend.",
      "De vlag wordt vervangen door het label middelmatig.",
    ],
    sleutel: "C",
    toelichtingGoed: "Onder 5 items met tijdgegevens wordt het aandeel wel berekend, maar nooit een vlag gezet. Vier tijdgegevens blijven dus onder het minimum.",
    toelichtingFout: "De denkfout is de berekening van het aandeel verwarren met het zetten van een vlag. De minimumregel van 5 blokkeert een vlag bij vier items.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.6",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "B",
    soort: "meerkeuze",
    stam: "Welke waarde heeft ITEM_TIJDSDREMPEL_MS in de afnamekwaliteitslogica van het instrument?",
    opties: [
      "200",
      "2.000",
      "5.000",
      "15.000",
    ],
    sleutel: "B",
    toelichtingGoed: "ITEM_TIJDSDREMPEL_MS is vastgelegd op 2000. De tijdsdrempel is daarmee een afzonderlijke parameter van de afnamekwaliteit.",
    toelichtingFout: "De denkfout is de tijdsdrempel verwarren met het minimum van 5 items of de 0,15-aandeeldrempel. De tijdsdrempel zelf is 2000 milliseconden.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.6",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een coach zegt dat de factoranalyse al als extern gepubliceerde bevestiging kan worden aangehaald. Welke reactie past bij de beschikbare onderbouwing?",
    opties: [
      "De statistische vormgeving is nagekeken door sectorfonds IVOC.",
      "Geen test-hertestonderzoek; stabiliteit over tijd niet gemeten.",
      "Geen normgroep; interpretatiedrempels zijn vastgesteld op inhoudelijk oordeel, niet op een empirische verdeling in een referentiegroep.",
      "De analyse is exploratief en niet extern gepubliceerd.",
    ],
    sleutel: "D",
    toelichtingGoed: "Dit is juist: de bron noemt de analyse exploratief en niet extern gepubliceerd.",
    toelichtingFout: "De overige uitspraken zijn wel brongegevens, maar zij beschrijven niet de publicatiestatus van de factoranalyse.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een adviseur wil de gerapporteerde factorladingen presenteren als een berekende betrouwbaarheidscoëfficiënt. Wat is de meest correcte begrenzing?",
    opties: [
      "Er is geen betrouwbaarheidscoëfficiënt, zoals Cronbachs alfa of McDonalds omega, berekend of gerapporteerd.",
      "De factorladingen voor de driverschalen liggen tussen 0,90 en 0,97.",
      "De factorladingen voor energieschalen onder de talentversnellers liggen tussen 0,63 en 0,84.",
      "Het extractiemodel, de fit-indices en de volledige factormatrix zijn niet gepubliceerd.",
    ],
    sleutel: "A",
    toelichtingGoed: "De bron vermeldt factorladingen, maar geen berekende of gerapporteerde betrouwbaarheidscoëfficiënt.",
    toelichtingFout: "De andere brongegevens gaan over factorladingen of de publicatiestatus, niet over een berekende betrouwbaarheidscoëfficiënt.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1 en §3.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "juistfout",
    stam: "Voor T4Professional is een betrouwbaarheidscoëfficiënt, zoals Cronbachs alfa of McDonalds omega, berekend of gerapporteerd.",
    opties: null,
    sleutel: "onjuist",
    toelichtingGoed: "Dit is onjuist: de bron vermeldt expliciet dat geen betrouwbaarheidscoëfficiënt is berekend of gerapporteerd.",
    toelichtingFout: "Een factorlading is niet de in de bron ontbrekende betrouwbaarheidscoëfficiënt zoals Cronbachs alfa of McDonalds omega.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een professional zegt dat een tweede afname na verloop van tijd dezelfde uitkomst zal bevestigen. Welke uitspraak bewaakt de grens het best?",
    opties: [
      "Er is geen normgroep; interpretatiedrempels zijn vastgesteld op inhoudelijk oordeel, niet op een empirische verdeling in een referentiegroep.",
      "De stabiliteit over tijd is niet gemeten, omdat er geen test-hertestonderzoek is.",
      "Het extractiemodel, de fit-indices en de volledige factormatrix zijn niet gepubliceerd.",
      "Externe inhoudsvalidatie door vier onafhankelijke experts onder supervisie van prof. dr. Peter Theuns.",
    ],
    sleutel: "B",
    toelichtingGoed: "Dit volgt rechtstreeks uit de bron: er is geen test-hertestonderzoek en stabiliteit over tijd is niet gemeten.",
    toelichtingFout: "De overige brongegevens noemen normgroep, publicatie en inhoudsvalidatie, maar meten geen stabiliteit over tijd.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Bij een nabespreking wil een adviseur de uitkomst als percentiel presenteren. Welke begrenzing sluit het nauwst aan bij de beschikbare onderbouwing?",
    opties: [
      "−2 wordt 0, 0 wordt 5 en +2 wordt 10; dit is rekenkunde, geen conventie.",
      "ENERGIE_TERUGVAL = 5 is de waarde bij ontbrekende meting.",
      "Er is geen normgroep; interpretatiedrempels zijn vastgesteld op inhoudelijk oordeel, niet op een empirische verdeling in een referentiegroep.",
      "De factorladingen voor driverschalen liggen tussen 0,90 en 0,97.",
    ],
    sleutel: "C",
    toelichtingGoed: "De bron meldt geen normgroep en noemt inhoudelijk oordeel, niet een empirische referentieverdeling, voor interpretatiedrempels.",
    toelichtingFout: "De andere uitspraken zijn brongegevens, maar alleen de juiste optie beschrijft het ontbreken van een normgroep en referentieverdeling.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een trainer wil zeggen dat extractiemodel, fit-indices en volledige factormatrix in een onderzoeksartikel beschikbaar zijn. Welke correctie is nodig?",
    opties: [
      "De statistische vormgeving is nagekeken door sectorfonds IVOC.",
      "De factorladingen van de driverschalen liggen tussen 0,90 en 0,97.",
      "Externe inhoudsvalidatie door vier onafhankelijke experts onder supervisie van prof. dr. Peter Theuns.",
      "Het extractiemodel, de fit-indices en de volledige factormatrix zijn niet gepubliceerd.",
    ],
    sleutel: "D",
    toelichtingGoed: "De bron noemt precies deze drie onderdelen als niet gepubliceerd en kwalificeert de analyse als niet extern gepubliceerd.",
    toelichtingFout: "IVOC, externe inhoudsvalidatie en de algemene status van de analyse beschrijven niet de publicatie van deze drie technische onderdelen.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een adviseur beschrijft de beoordeling door externe experts als een afzonderlijk gepubliceerd rapport. Welke formulering is wel juist?",
    opties: [
      "Vier onafhankelijke experts voerden externe inhoudsvalidatie uit, maar de bevindingen zijn niet als afzonderlijk rapport gepubliceerd.",
      "De statistische vormgeving is nagekeken door sectorfonds IVOC.",
      "Geen betrouwbaarheidscoëfficiënt, zoals Cronbachs alfa of McDonalds omega, berekend of gerapporteerd.",
      "Geen normgroep; interpretatiedrempels zijn vastgesteld op inhoudelijk oordeel, niet op een empirische verdeling in een referentiegroep.",
    ],
    sleutel: "A",
    toelichtingGoed: "De bron vermeldt externe inhoudsvalidatie door vier onafhankelijke experts en vermeldt dat de bevindingen niet afzonderlijk zijn gepubliceerd.",
    toelichtingFout: "De andere brongegevens gaan over IVOC, betrouwbaarheid en normgroep, niet over de expertbeoordeling en haar publicatiestatus.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "meerkeuze",
    stam: "Welke omschrijving van de bijdrage van sectorfonds IVOC aan de onderbouwing van T4Professional is volgens de bron correct?",
    opties: [
      "Geen normgroep; interpretatiedrempels zijn vastgesteld op inhoudelijk oordeel, niet op een empirische verdeling in een referentiegroep.",
      "IVOC heeft de statistische vormgeving nagekeken.",
      "Geen test-hertestonderzoek; stabiliteit over tijd niet gemeten.",
      "Geen betrouwbaarheidscoëfficiënt, zoals Cronbachs alfa of McDonalds omega, berekend of gerapporteerd.",
    ],
    sleutel: "B",
    toelichtingGoed: "De bron schrijft aan IVOC alleen het nakijken van de statistische vormgeving toe.",
    toelichtingFout: "De andere brongegevens beschrijven expliciete lacunes, terwijl de juiste optie de specifieke rol van IVOC weergeeft.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een consultant wil uit een profiel afleiden dat functioneren, welbevinden en verloop voorspeld zijn. Welke begrenzing is volgens de bron correct?",
    opties: [
      "De factorladingen voor driverschalen liggen tussen 0,90 en 0,97.",
      "Externe inhoudsvalidatie door vier onafhankelijke experts onder supervisie van prof. dr. Peter Theuns.",
      "Samenhang met uitkomsten buiten het instrument, waaronder functioneren, welbevinden en verloop, is niet onderzocht.",
      "Geen betrouwbaarheidscoëfficiënt, zoals Cronbachs alfa of McDonalds omega, berekend of gerapporteerd.",
    ],
    sleutel: "C",
    toelichtingGoed: "De bron stelt expliciet dat de samenhang met uitkomsten buiten het instrument niet is onderzocht.",
    toelichtingFout: "Factorladingen, inhoudsvalidatie en betrouwbaarheidscoëfficiënten beschrijven geen onderzocht verband met uitkomsten buiten het instrument.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Na een afname noemt een leidinggevende het resultaat een definitief oordeel over wat de deelnemer kan. Welke reactie volgt de claimgrens?",
    opties: [
      "Geen test-hertestonderzoek; stabiliteit over tijd niet gemeten.",
      "Geen normgroep; interpretatiedrempels zijn vastgesteld op inhoudelijk oordeel, niet op een empirische verdeling in een referentiegroep.",
      "De vragenlijst is zorgvuldig ingevuld, dus het resultaat mag als vaststaand gelden.",
      "Een resultaat is een momentopname op het ogenblik van afname, geen vaststaand oordeel over iemands mogelijkheden.",
    ],
    sleutel: "D",
    toelichtingGoed: "De claimgrens formuleert woordelijk dat een resultaat een momentopname is en geen vaststaand oordeel over mogelijkheden.",
    toelichtingFout: "De overige uitspraken zijn brongegevens, maar alleen de juiste optie begrenst het resultaat als momentopname van de afname.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een leidinggevende wil een T4Professional-profiel als enige basis gebruiken voor een promotiebeslissing. Welke reactie past bij de claimgrens?",
    opties: [
      "Het profiel is een gespreksinstrument en mag niet als enige basis dienen voor beslissingen over promotie.",
      "De analyse is exploratief en niet extern gepubliceerd.",
      "De factorladingen voor driverschalen liggen tussen 0,90 en 0,97.",
      "IVOC heeft de statistische vormgeving nagekeken.",
    ],
    sleutel: "A",
    toelichtingGoed: "De claimgrens noemt het profiel een gespreksinstrument en sluit uit dat het de enige basis is voor promotiebeslissingen.",
    toelichtingFout: "De overige brongegevens zeggen niets over de expliciete grens dat een profiel niet de enige basis voor promotie mag zijn.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een coach verklaart dat een score van 7,4 inhoudelijk wezenlijk verschilt van een score van 7,6. Welke reactie is juist?",
    opties: [
      "Hoog begint bij 7,5.",
      "Er bestaat geen onderzoek waaruit volgt dat een 7,4 wezenlijk anders is dan een 7,6.",
      "−2 wordt 0, 0 wordt 5 en +2 wordt 10; dit is rekenkunde, geen conventie.",
      "Stevig begint bij 5 en wisselend begint bij 3.",
    ],
    sleutel: "B",
    toelichtingGoed: "Dit is woordelijk de grens uit de bron: er bestaat geen onderzoek dat een wezenlijk verschil tussen 7,4 en 7,6 onderbouwt.",
    toelichtingFout: "De andere uitspraken beschrijven schaalwaarden of bandstarts, maar alleen de juiste optie betreft de ontbrekende empirische betekenis van 7,4 en 7,6.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.5",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "juistfout",
    stam: "Alle bandgrenzen van de energieschaal zijn empirisch geijkt op een normgroep en vormen daarom een meting.",
    opties: null,
    sleutel: "onjuist",
    toelichtingGoed: "Dit is onjuist: alle bandgrenzen zijn conventies van de ontwikkelaar en niet empirisch geijkt op een normgroep.",
    toelichtingFout: "De bron onderscheidt de herschaling als rekenkunde van de bandgrenzen, die juist conventies en geen empirische ijking zijn.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.5",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een rapporteur noemt het label hoog bij 7,6 een empirisch vastgesteld kwaliteitsverschil. Welke formulering bewaakt de juiste grens?",
    opties: [
      "−2 wordt 0, 0 wordt 5 en +2 wordt 10; dit is rekenkunde, geen conventie.",
      "Geen test-hertestonderzoek; stabiliteit over tijd niet gemeten.",
      "Hoog begint bij 7,5, maar alle bandgrenzen zijn conventies van de ontwikkelaar.",
      "Geen betrouwbaarheidscoëfficiënt, zoals Cronbachs alfa of McDonalds omega, berekend of gerapporteerd.",
    ],
    sleutel: "C",
    toelichtingGoed: "De bron geeft 7,5 als start van hoog, maar noemt alle bandgrenzen conventies van de ontwikkelaar.",
    toelichtingFout: "Alleen de juiste optie koppelt de startwaarde 7,5 aan de bronuitspraak dat bandgrenzen conventies van de ontwikkelaar zijn.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.5",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "meerkeuze",
    stam: "Welke omschrijving van de exploratieve factoranalyse bevat de aantallen en betrokken Universiteit Antwerpen-professoren zoals de bron die noemt?",
    opties: [
      "Externe inhoudsvalidatie door vier onafhankelijke experts onder supervisie van prof. dr. Peter Theuns.",
      "De statistische vormgeving is nagekeken door sectorfonds IVOC.",
      "De analyse is exploratief en niet extern gepubliceerd.",
      "1.858 T4Professional-profielen en 395 profielen van het sportinstrument, met prof. dr. Guido Van Hal en prof. dr. Stefan Van Dongen.",
    ],
    sleutel: "D",
    toelichtingGoed: "De bron noemt precies 1.858 T4Professional-profielen, 395 sportprofielen en de twee professoren van de Universiteit Antwerpen.",
    toelichtingFout: "De overige uitspraken gaan over inhoudsvalidatie, IVOC of de algemene publicatiestatus, niet over aantallen en Antwerpen-professoren van de factoranalyse.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "C",
    soort: "scenario",
    stam: "Een professional vergelijkt de gerapporteerde factorladingen van drivers met die van energieschalen onder de talentversnellers. Welke weergave is correct?",
    opties: [
      "Driverschalen 0,90–0,97; energieschalen onder de talentversnellers 0,63–0,84.",
      "Geen betrouwbaarheidscoëfficiënt, zoals Cronbachs alfa of McDonalds omega, berekend of gerapporteerd.",
      "Geen test-hertestonderzoek; stabiliteit over tijd niet gemeten.",
      "Geen normgroep; interpretatiedrempels zijn vastgesteld op inhoudelijk oordeel, niet op een empirische verdeling in een referentiegroep.",
    ],
    sleutel: "A",
    toelichtingGoed: "De bron rapporteert 0,90–0,97 voor driverschalen en 0,63–0,84 voor energieschalen onder de talentversnellers.",
    toelichtingFout: "Betrouwbaarheid, test-hertest en normgroep zijn andere onderbouwingspunten en vervangen de bronvermelding van de twee factorladingreeksen niet.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een coach vergelijkt de net-score van twee deelnemers en concludeert dat de deelnemer met de hoogste net-score dat construct duidelijk sterker bezit. Welke reactie herkent de interpretatiefout het best?",
    opties: [
      "De conclusie klopt alleen wanneer beide deelnemers evenveel blokken invulden.",
      "De conclusie is te stellig, want net is ipsatief en vergelijkt constructen binnen één persoon onderling.",
      "De conclusie klopt, want net telt de keuzes als meest herkenbaar op.",
      "De conclusie klopt alleen als beide deelnemers dezelfde energiewaarden doorgaven.",
    ],
    sleutel: "B",
    toelichtingGoed: "Net ontstaat uit keuzes binnen blokken en beschrijft hoe constructen zich bij één deelnemer onderling verhouden. Het is daarom geen directe maat om twee personen onderling te rangschikken.",
    toelichtingFout: "De afleiders behandelen net als een persoonsvergelijkende score of voegen voorwaarden toe die de ipsatieve aard niet wegnemen. Daardoor blijft de kernfout bestaan.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een adviseur noemt een net-score van een deelnemer ‘boven het gemiddelde van vergelijkbare professionals’, terwijl hij alleen het individuele profiel ziet. Waarom is deze duiding fout?",
    opties: [
      "Een net-score kan uitsluitend negatief worden geïnterpreteerd.",
      "Een gemiddelde mag alleen worden genoemd wanneer energie op itemniveau is gemeten.",
      "Er is geen normgroep of referentieverdeling waarmee zo’n gemiddelde kan worden onderbouwd.",
      "Het profiel bevat te weinig constructen om een gemiddelde te berekenen.",
    ],
    sleutel: "C",
    toelichtingGoed: "Voor het instrument bestaat geen normgroep. Zonder empirische referentiegroep is een uitspraak over gemiddeld of bovengemiddeld bij vergelijkbare professionals niet verantwoord.",
    toelichtingFout: "De afleiders noemen beperkingen die niet de ontbrekende referentieverdeling verklaren. Juist het ontbreken van een normgroep maakt deze vergelijking onbewezen.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.1 en §3.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "In een rapport staat avgEnergy = 0. De begeleider zegt meteen dat de deelnemer dit construct neutraal heeft ervaren. Wat is de beste correctie?",
    opties: [
      "Dat is zeker juist, want nul is altijd een ingevulde neutrale energiewaarde.",
      "Dat is alleen juist bij drivers, omdat daar energie per item wordt bevraagd.",
      "Dat betekent dat de deelnemer even vaak positieve als negatieve energie rapporteerde.",
      "Dat kan niet worden vastgesteld: nul kan zowel neutraal gemeten energie als het ontbreken van energiewaarden betekenen.",
    ],
    sleutel: "D",
    toelichtingGoed: "De scorelogica geeft avgEnergy de waarde 0 wanneer er geen energiewaarden zijn. Omdat 0 ook het label neutraal op de energieschaal is, laat dit getal die twee situaties niet onderscheiden.",
    toelichtingFout: "De andere antwoorden doen alsof nul eenduidig een gemeten ervaring of een balans van metingen toont. De terugval bij ontbrekende energiewaarden maakt die zekerheid onjuist.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.1",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een dashboard toont voor een ontbrekende energiemeting de waarde 5. Een manager zegt dat de deelnemer dus precies neutrale energie rapporteerde. Welke interpretatie is correct?",
    opties: [
      "De conclusie is fout: 5 bij ontbrekende meting is een conventionele terugval en geen gemeten energie.",
      "De manager heeft gelijk, omdat 5 altijd een feitelijk gemeten energiewaarde is.",
      "De manager heeft gelijk, maar alleen wanneer alle blokken zijn ingevuld.",
      "De conclusie is alleen onjuist als de deelnemer een lage net-score heeft.",
    ],
    sleutel: "A",
    toelichtingGoed: "ENERGIE_TERUGVAL = 5 is volgens de bron een conventie voor een ontbrekende meting. De aanwezigheid van die waarde toont dus niet dat de deelnemer neutrale energie heeft gemeld.",
    toelichtingFout: "De andere antwoorden maken van de terugvalwaarde alsnog een waarneming of verbinden die aan irrelevante voorwaarden. Daarmee wordt een ontbrekende meting ten onrechte als resultaat gelezen.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.5",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Twee energiescores liggen dicht bij elkaar: 7,4 en 7,6. Een rapporteur stelt dat de tweede score aantoonbaar wezenlijk beter is omdat die boven de bandgrens voor hoog ligt. Wat is de juiste reactie?",
    opties: [
      "De rapporteur heeft gelijk, want elke grensoverschrijding bewijst een betekenisvol verschil.",
      "De bandgrenzen zijn conventies en niet empirisch geijkt; het dossier onderbouwt geen wezenlijk verschil tussen 7,4 en 7,6.",
      "De tweede score is alleen wezenlijk beter wanneer de eerste score uit een driver komt.",
      "Het verschil is alleen aantoonbaar wanneer beide scores op een tienschaal staan.",
    ],
    sleutel: "B",
    toelichtingGoed: "De bron vermeldt uitdrukkelijk dat de bandgrenzen ontwikkelaarsconventies zijn en niet op een normgroep zijn geijkt. Zij geeft juist 7,4 en 7,6 als voorbeeld zonder aangetoond wezenlijk verschil.",
    toelichtingFout: "De afleiders verwarren een classificatiegrens met empirisch bewijs of voegen voorwaarden toe die daarvoor geen onderbouwing bieden. Een labelwissel maakt het verschil niet aantoonbaar.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.5",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een professional legt uit dat het label driverRisk het gemiddelde is van de avgEnergy van alle vijf drivers. Welke correctie is nodig?",
    opties: [
      "Dat klopt, want alle drivers worden eerst op energie gerangschikt.",
      "Dat klopt alleen wanneer de vijf drivers allemaal een net-score boven nul hebben.",
      "Dat is fout: driverRisk gebruikt uitsluitend de twee drivers met de hoogste net-score.",
      "Dat is fout, want driverRisk gebruikt uitsluitend de driver met de laagste net-score.",
    ],
    sleutel: "C",
    toelichtingGoed: "Voor driverRisk worden de drivers eerst aflopend op net gesorteerd. Alleen de top twee worden vervolgens gebruikt om het gemiddelde en daarmee het label te bepalen.",
    toelichtingFout: "De andere antwoorden rekenen met alle drivers, met een onjuiste sorteervolgorde of met één laagste driver. Geen daarvan beschrijft de vastgelegde selectie van de top twee.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "De derde driver op net-score heeft sterk negatieve avgEnergy. Een begeleider verklaart een laag driverRisk-label uitsluitend vanuit die derde driver. Waarom is dat onjuist?",
    opties: [
      "Omdat negatieve avgEnergy nooit invloed heeft op een driverRisk-label.",
      "Omdat alleen drivers met positieve avgEnergy voor driverRisk meetellen.",
      "Omdat de derde driver altijd dezelfde net-score heeft als de eerste twee.",
      "Omdat driverRisk alleen de top twee drivers op net-score gebruikt; de derde driver zit niet in die labelberekening.",
    ],
    sleutel: "D",
    toelichtingGoed: "De labelberekening beperkt zich tot de twee drivers met de hoogste net-score. De energie van de derde driver kan daarom niet de directe verklaring zijn voor het berekende driverRisk-label.",
    toelichtingFout: "De afleiders ontkennen ten onrechte de rol van negatieve energie, hanteren een verkeerde selectievoorwaarde of doen een ongefundeerde uitspraak over gelijke net-scores.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Na een lage consistentiescore zegt een coach tegen de deelnemer: ‘U bent als persoon niet consistent.’ Welke reactie benoemt de interpretatiefout?",
    opties: [
      "Dat is fout: de consistentiescore gaat over de innerlijke samenhang van de gegeven antwoorden, niet over de persoon.",
      "Dat is juist, want de score is een diagnose van een persoonlijke eigenschap.",
      "Dat is juist wanneer de deelnemer alle keuzeparen volledig invulde.",
      "Dat is fout, want consistentie wordt uitsluitend uit de zelfgemelde beroepsenergie bepaald.",
    ],
    sleutel: "A",
    toelichtingGoed: "De bron omschrijft de consistentiemaat als een beoordeling van de innerlijke samenhang van de antwoorden. Zij mag daarom niet worden omgezet in een oordeel over iemands persoonlijke consistentie.",
    toelichtingFout: "De andere reacties behandelen de score als persoonsdiagnose of beschrijven onjuist hoe die wordt berekend. Daarmee schuiven zij de betekenis van antwoordpatroon naar persoon op.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een assessor zegt dat een deelnemer met uitgesproken positieve en negatieve energie op alle drivers extra punten krijgt voor het onderdeel spreadPart. Welke correctie past hierbij?",
    opties: [
      "Dat klopt, want spreadPart beloont grote verschillen tussen energiewaarden.",
      "Dat is fout: spreadPart is hoger bij kleinere energiespreiding, zodat uitgesproken energie op alle drivers punten op dit deel kan kosten.",
      "Dat klopt alleen wanneer de drie hoogste drivers positieve avgEnergy hebben.",
      "Dat is fout, want spreadPart telt uitsluitend energiewaarden van talent-foci mee.",
    ],
    sleutel: "B",
    toelichtingGoed: "SpreadPart daalt wanneer energySpread groter wordt. Omdat energySpread de som van de absolute avgEnergy over alle drivers is, verliest een uitgesproken patroon juist punten op dit onderdeel.",
    toelichtingFout: "De afleiders keren de richting van spreadPart om of beperken de berekening ten onrechte tot een andere selectie. Zij passen dus niet bij de beschreven scorelogica.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een deelnemer schat de eigen beroepsenergie hoger in dan de genormaliseerde energie uit de vragenlijst. De rapporteur noemt een positieve energyDiscrepancy een teken van onderschatting. Wat is correct?",
    opties: [
      "De rapporteur heeft gelijk, want positieve discrepantie betekent altijd onderschatting.",
      "Een positieve discrepantie kan niet voorkomen bij zelfgemelde beroepsenergie.",
      "De rapporteur heeft de richting omgedraaid: positief betekent dat de deelnemer zichzelf hoger inschat dan de vragenlijst uitwijst.",
      "De richting hangt uitsluitend af van het aantal ingevulde blokken.",
    ],
    sleutel: "C",
    toelichtingGoed: "EnergyDiscrepancy wordt berekend als baseline min genormaliseerde vragenlijstenergie. Bij een positieve uitkomst is de zelfingeschatte beroepsenergie dus hoger dan de uitkomst uit de vragenlijst.",
    toelichtingFout: "De andere antwoorden draaien de aftrekrichting om, ontkennen de mogelijkheid van een positieve uitkomst of noemen een voorwaarde die niet bepalend is voor de richting.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.4",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een afname krijgt een waarschuwing over de invulwijze. De leidinggevende schrijft in het dossier dat dit bewijst dat de deelnemer onzorgvuldig en onbetrouwbaar is. Wat is de juiste reactie?",
    opties: [
      "De waarschuwing is een diagnose van de betrouwbaarheid van de deelnemer.",
      "De waarschuwing toont dat het gehele profiel inhoudelijk ongeldig is.",
      "De waarschuwing betekent dat de deelnemer geen energievragen heeft beantwoord.",
      "De waarschuwing is uitdrukkelijk geen oordeel over de persoon; zij zegt alleen iets over de manier waarop deze vragenlijst is ingevuld.",
    ],
    sleutel: "D",
    toelichtingGoed: "Afnamekwaliteit is volgens de bron geen score, eigenschap of diagnose van de persoon. De uitkomst betreft uitsluitend de manier waarop deze ene vragenlijst is ingevuld.",
    toelichtingFout: "De afleiders maken van een signaal over de afname een persoonskenmerk, een oordeel over alle profielinhoud of een specifieke ontbrekende vraagsoort. Dat gaat verder dan de bron toestaat.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.6",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Bij een afname zijn tijdgegevens beschikbaar voor vier items. Een systeembeheerder wil op basis van het berekende aandeel snelle antwoorden toch een afnamevlag tonen. Welke beoordeling is juist?",
    opties: [
      "Onder vijf items met tijdgegevens wordt nooit een vlag gezet, ook al wordt het aandeel wel berekend.",
      "Een vlag is verplicht zodra ook maar één tijdgegeven beschikbaar is.",
      "Een vlag is juist wanneer meer dan de helft van de vier antwoorden snel is gegeven.",
      "Een vlag is juist zolang de deelnemer niet alle blokken heeft voltooid.",
    ],
    sleutel: "A",
    toelichtingGoed: "De bron legt een minimum van vijf items met tijdgegevens vast. Onder dat minimum kan het aandeel wel worden berekend, maar de afnamekwaliteit zet nooit een vlag.",
    toelichtingFout: "De andere antwoorden vervangen het expliciete minimum door een ander criterium. Zij negeren daarmee de regel dat minder dan vijf tijdmetingen nooit tot een vlag leidt.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.6",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een manager ziet één profiel en stelt dat dit definitief vastlegt welke mogelijkheden de deelnemer ook in de toekomst zal hebben. Welke beoordeling van die conclusie volgt de claimgrens?",
    opties: [
      "De conclusie klopt, omdat een profiel iemands mogelijkheden duurzaam meet.",
      "De conclusie is fout: het resultaat is een momentopname op het ogenblik van afname en geen vaststaand oordeel over mogelijkheden.",
      "De conclusie klopt alleen wanneer de deelnemer alle energiewaarden heeft ingevuld.",
      "De conclusie is fout, omdat resultaten uitsluitend op papier mogen worden besproken.",
    ],
    sleutel: "B",
    toelichtingGoed: "De claimgrens noemt een profiel een momentopname en verbiedt een vaststaand oordeel over iemands mogelijkheden. De manager maakt precies die niet-toegestane stap van moment naar permanente conclusie.",
    toelichtingFout: "De afleiders behandelen het profiel als een duurzame meting, koppelen de fout aan irrelevante volledigheid of voegen een beperking toe die niet in de claimgrens staat.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een coach vergelijkt twee afnames van dezelfde deelnemer en zegt dat een verschil in score bewijst dat diens profiel stabiel genoeg is om veranderingen precies te meten. Wat ontbreekt aan deze redenering?",
    opties: [
      "Niets; de bron rapporteert test-hertestonderzoek als bewijs voor stabiliteit.",
      "De redenering is alleen fout wanneer een van beide afnames tijdgegevens mist.",
      "Stabiliteit over tijd is niet gemeten, omdat er geen test-hertestonderzoek is gerapporteerd.",
      "De redenering is juist als beide afnames dezelfde bandgrens krijgen.",
    ],
    sleutel: "C",
    toelichtingGoed: "In de onderbouwing staat dat test-hertestonderzoek ontbreekt en stabiliteit over tijd niet is gemeten. Een verschil tussen twee afnames kan daarom niet als bewezen precisie of stabiliteit worden uitgelegd.",
    toelichtingFout: "De andere antwoorden voegen niet-gerapporteerd bewijs toe of stellen voorwaarden die het ontbrekende stabiliteitsonderzoek niet vervangen. Daarmee maken zij de conclusie onterecht zeker.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een opdrachtgever wil uit een profiel afleiden dat een deelnemer aantoonbaar beter zal functioneren in toekomstige projecten. Welke reactie bewaakt de interpretatiegrens?",
    opties: [
      "Dat is verantwoord, want de samenhang met functioneren is in het instrument vastgesteld.",
      "Dat is alleen verantwoord wanneer de driverRisk-score laag is.",
      "Dat is onjuist, omdat het instrument geen enkele score berekent.",
      "Dat is niet onderbouwd, want samenhang met uitkomsten buiten het instrument, zoals functioneren, is niet onderzocht.",
    ],
    sleutel: "D",
    toelichtingGoed: "De bron vermeldt dat de samenhang met uitkomsten buiten het instrument, waaronder functioneren, niet is onderzocht. Het profiel kan daarom geen aantoonbare voorspelling van toekomstig functioneren dragen.",
    toelichtingFout: "De afleiders doen alsof externe samenhang is vastgesteld, koppelen die aan een interne labelscore of ontkennen ten onrechte alle scoreberekeningen. Geen daarvan respecteert de onderzoeksgrens.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.2",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "D",
    soort: "scenario",
    stam: "Een rapporteur legt het label midden uit alsof daarvoor eigen numerieke bandgrenzen bestaan. Welke correctie is volgens de energieschaal het meest precies?",
    opties: [
      "Dat is fout: midden is een samenvoeging zonder eigen getallen.",
      "Dat klopt, want midden heeft een eigen grens tussen stevig en wisselend.",
      "Dat klopt alleen wanneer alle energiewaarden uit de vragenlijst komen.",
      "Midden heeft eigen grenzen, maar uitsluitend voor drivers.",
    ],
    sleutel: "A",
    toelichtingGoed: "De driedeling hoog, midden en laag is volgens de bron een samenvoeging zonder eigen getallen. Een apart label midden kan daarom niet als zelfstandig afgebakende band worden gelezen.",
    toelichtingFout: "De afleiders kennen aan midden een eigen grens toe of laten die afhangen van de energiebron of familie. Zulke afzonderlijke bandgrenzen zijn niet vastgelegd in de energieschaal.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.5",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een vrijwillige deelnemer start een afname van het T4P Business Kompas. Welke rechtsgrond hoort volgens het dossier standaard bij deze afname?",
    opties: [
      "Gerechtvaardigd belang, omdat de deelnemer een vragenlijst invult.",
      "Toestemming, omdat de deelnemer vrijwillig invult en die kan intrekken.",
      "Overeenkomst, omdat elke ingevulde vragenlijst een licentieovereenkomst is.",
      "Wettelijke verplichting, omdat het instrument persoonsgegevens verwerkt.",
    ],
    sleutel: "B",
    toelichtingGoed: "Bij een afname van een deelnemer is toestemming de standaardrechtsgrond. De vrijwillige deelnemer kan die toestemming ook intrekken.",
    toelichtingFout: "Overeenkomst is in dit dossier de standaardrechtsgrond voor een bekwaamheidsronde van een geaccrediteerde, niet voor een deelnemer-afname.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §4",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een geaccrediteerde legt binnen zijn licentie een bekwaamheidsproef af. Welke rechtsgrond geldt hiervoor volgens het dossier standaard?",
    opties: [
      "Toestemming, omdat een proef altijd vrijwillig is.",
      "Gerechtvaardigd belang, omdat de proef de kwaliteit bewaakt.",
      "Overeenkomst, omdat de bekwaamheidsproef binnen een licentieovereenkomst plaatsvindt.",
      "Een wettelijke verplichting, omdat accreditatie verplicht geregistreerd moet worden.",
    ],
    sleutel: "C",
    toelichtingGoed: "Voor bekwaamheidsrondes van geaccrediteerden staat overeenkomst als standaardrechtsgrond geregistreerd. De proef vindt plaats binnen de licentieovereenkomst.",
    toelichtingFout: "Toestemming is de standaardrechtsgrond voor de vrijwillige deelnemer-afname. Het dossier maakt juist inhoudelijk onderscheid met de bekwaamheidsproef.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §4",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een deelnemer meldt tijdens een lopende afname dat hij zijn toestemming intrekt. Wat is de passende onmiddellijke consequentie voor de verwerking?",
    opties: [
      "De verwerking loopt door tot de afname automatisch is afgerond.",
      "Alleen toekomstige rapporten worden tegengehouden; de verwerking zelf verandert niet.",
      "De toestemming wordt vervangen door de licentieovereenkomst van de coach.",
      "De verwerking stopt, omdat er zonder toestemming geen rechtsgrond meer is.",
    ],
    sleutel: "D",
    toelichtingGoed: "Het dossier bepaalt uitdrukkelijk dat het intrekken van toestemming gevolg moet hebben. Zonder rechtsgrond stopt de verwerking.",
    toelichtingFout: "Een ingetrokken toestemming mag niet zonder gevolg blijven. De deelnemer-afname steunt standaard op toestemming en de verwerking stopt dan.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §4",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een geaccrediteerde wil zijn bekwaamheidsronde stopzetten en vraagt om zijn toestemming in te trekken. Welke uitleg sluit aan bij het dossier?",
    opties: [
      "De ronde is standaard gebaseerd op overeenkomst; presenteer dit niet als een deelnemerstoestemming die kan worden ingetrokken.",
      "De ronde is standaard gebaseerd op toestemming, dus intrekken is het juiste kader.",
      "Elke bekwaamheidsronde is gebaseerd op een wettelijke verplichting.",
      "De rechtsgrond hangt uitsluitend af van de voorkeur van de geaccrediteerde.",
    ],
    sleutel: "A",
    toelichtingGoed: "Een bekwaamheidsproef van een geaccrediteerde valt volgens het dossier standaard onder overeenkomst, binnen een licentieovereenkomst.",
    toelichtingFout: "Wie de rechtsgronden verwisselt, belooft de geaccrediteerde ten onrechte een intrekkingsrecht dat bij toestemming van een deelnemer hoort.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §4",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een beheerder controleert de registratie van een deelnemer-afname. Welke combinatie moet volgens het dossier in de afnametabel aanwezig zijn naast de rechtsgrond?",
    opties: [
      "Alleen het tijdstip en de naam van de coach.",
      "Het verwerkingsdoel en de versie van de privacyverklaring.",
      "Alleen het rapportformat en de energiebalk.",
      "De bewaartermijn en een lijst met externe verwerkers.",
    ],
    sleutel: "B",
    toelichtingGoed: "De twee relevante tabellen dragen naast de rechtsgrond ook verwerkingsdoel en privacyverklaring_versie. Die gegevens leggen doel en informatieversie vast.",
    toelichtingFout: "Het dossier noemt voor beide tabellen het verwerkingsdoel en de privacyverklaring_versie. Het noemt hier geen bewaartermijn of namen van verwerkers.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §4",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een werkgever wil bestaande profielgegevens later gebruiken voor een intern onderzoeksproject dat niet het oorspronkelijke verwerkingsdoel is. Wat verlangt doelbinding eerst?",
    opties: [
      "De gegevens zonder verdere beoordeling hergebruiken, omdat de werkgever ze al bezit.",
      "De werkgever mag het doel achteraf aanpassen zonder de betrokkenen te informeren.",
      "Eerst beoordelen of het nieuwe gebruik verenigbaar is met het oorspronkelijke doel of een passende nieuwe grondslag vereist.",
      "De gegevens onmiddellijk openbaar maken, zodat het nieuwe doel transparant wordt.",
    ],
    sleutel: "C",
    toelichtingGoed: "Doelbinding begrenst verder gebruik van persoonsgegevens. Een ander doel vraagt eerst een beoordeling van verenigbaarheid of een passende nieuwe grondslag.",
    toelichtingFout: "Dat een organisatie gegevens al bezit, maakt elk later gebruik niet automatisch toegestaan. Het oorspronkelijke verwerkingsdoel blijft richtinggevend.",
    gebruik: "meten",
    bronVerwijzing: "AVG: doelbinding",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Vóór een deelnemer persoonsgegevens invult, wil hij weten waarvoor zijn gegevens worden gebruikt. Welke informatie moet in elk geval duidelijk beschikbaar zijn?",
    opties: [
      "Alleen de naam van het instrument en de invulduur.",
      "Alleen de technische methode waarmee de score wordt berekend.",
      "Een mondelinge belofte dat de gegevens nooit worden geraadpleegd.",
      "Het verwerkingsdoel en de toepasselijke privacyverklaring, in begrijpelijke vorm.",
    ],
    sleutel: "D",
    toelichtingGoed: "Transparantie vereist dat de betrokkene begrijpelijk wordt geïnformeerd over de verwerking. Het dossier registreert bovendien doel en versie van de privacyverklaring.",
    toelichtingFout: "Alleen een instrumentnaam of invulduur vertelt niet waarvoor persoonsgegevens worden verwerkt. Het verwerkingsdoel en de privacy-informatie moeten duidelijk zijn.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §4; AVG: transparantie",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een leidinggevende vraagt zonder nadere toelichting alle individuele rapporten van het team op. Wat is de meest privacybewuste eerste reactie?",
    opties: [
      "Eerst nagaan of er voor deze toegang een passend, duidelijk doel en een geldige grondslag bestaat.",
      "De rapporten meteen delen, want de leidinggevende heeft een hiërarchische rol.",
      "De rapporten aan alle teamleden doorsturen, zodat de behandeling gelijk is.",
      "De leidinggevende laten kiezen welke rapporten inhoudelijk het interessantst zijn.",
    ],
    sleutel: "A",
    toelichtingGoed: "Een leidinggevende krijgt niet automatisch toegang tot alle persoonsgegevens. Voor verstrekking moet het doel duidelijk zijn en moet een geldige grondslag bestaan.",
    toelichtingFout: "Een hiërarchische positie op zichzelf rechtvaardigt geen onbeperkte inzage. Persoonsgegevens mogen niet los van doel en grondslag worden gedeeld.",
    gebruik: "meten",
    bronVerwijzing: "AVG: rechtmatigheid en doelbinding",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een organisatie wil een medewerker niet promoveren uitsluitend omdat een profielresultaat volgens haar ongunstig oogt. Welke handelwijze past bij de claimgrens?",
    opties: [
      "Het profiel als enige grond gebruiken, zolang de score hoog genoeg is.",
      "Het profiel gebruiken als gespreksinput, maar niet als enige basis voor de promotiebeslissing.",
      "De uitkomst behandelen als een vast oordeel over de mogelijkheden van de medewerker.",
      "De medewerker vragen vooraf te tekenen dat de score doorslaggevend mag zijn.",
    ],
    sleutel: "B",
    toelichtingGoed: "Het profiel is een gespreksinstrument met inzichten en richtingaanwijzers. Het mag niet als enige basis dienen voor een beslissing over promotie.",
    toelichtingFout: "Volgens de claimgrens is een resultaat een momentopname en geen vaststaand oordeel. Een profiel mag daarom niet alleen de promotiebeslissing dragen.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Bij een afname worden enkele zeer korte invultijden gesignaleerd. Een coach noemt de deelnemer daarop onzorgvuldig en ongeschikt. Wat is de correcte duiding?",
    opties: [
      "De afnamekwaliteit bewijst een blijvende eigenschap van de deelnemer.",
      "De afnamekwaliteit is een diagnose van de persoonlijkheid van de deelnemer.",
      "De afnamekwaliteit zegt alleen iets over de manier waarop deze ene vragenlijst is ingevuld.",
      "Een tijdssignaal betekent dat het volledige profiel inhoudelijk ongeldig is.",
    ],
    sleutel: "C",
    toelichtingGoed: "De uitkomst over afnamekwaliteit is uitdrukkelijk geen oordeel over de persoon. Ze gaat uitsluitend over de wijze van invullen van deze ene vragenlijst.",
    toelichtingFout: "Een afnamekwaliteitssignaal is volgens het dossier geen score, eigenschap of diagnose. Het mag dus niet als persoonsbeoordeling worden voorgesteld.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §2.6",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "In een gesprek stelt een coach dat het profiel definitief vastlegt wat een deelnemer wel en niet kan. Welke correctie is nodig?",
    opties: [
      "Dat klopt, want een profiel is een blijvende vaststelling van mogelijkheden.",
      "Dat klopt alleen wanneer de deelnemer het rapport heeft ondertekend.",
      "Een profielresultaat geldt alleen als vaststaand oordeel bij een tweede afname.",
      "Een profielresultaat is een momentopname en geen vaststaand oordeel over iemands mogelijkheden.",
    ],
    sleutel: "D",
    toelichtingGoed: "De claimgrens omschrijft een resultaat als een momentopname op het moment van afname. Het is geen vaststaand oordeel over iemands mogelijkheden.",
    toelichtingFout: "Het dossier laat niet toe om een profiel als definitieve vaststelling van mogelijkheden te presenteren. De juiste duiding blijft die van een momentopname.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §3.3",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een werkgever wil software automatisch laten bepalen welke medewerkers een ingrijpende arbeidsbeslissing krijgen, uitsluitend op basis van profielgegevens. Welk AVG-punt is hierbij centraal?",
    opties: [
      "De bijzondere bescherming rond uitsluitend geautomatiseerde besluiten met rechtsgevolgen of vergelijkbare significante gevolgen moet worden nageleefd.",
      "Een volledig geautomatiseerde, ingrijpende beslissing mag zonder extra beoordeling altijd worden uitgevoerd.",
      "Het volstaat dat de werkgever de betrokkene achteraf informeert over het genomen besluit.",
      "Geautomatiseerde besluiten vallen buiten de AVG wanneer er een profiel wordt gebruikt.",
    ],
    sleutel: "A",
    toelichtingGoed: "Artikel 22 AVG geeft betrokkenen bijzondere bescherming tegen uitsluitend geautomatiseerde individuele besluiten met rechtsgevolgen of vergelijkbaar significante gevolgen.",
    toelichtingFout: "Een ingrijpend besluit verdwijnt niet buiten de AVG omdat software het uitvoert. Juist uitsluitend geautomatiseerde besluitvorming vraagt bijzondere aandacht.",
    gebruik: "meten",
    bronVerwijzing: "AVG art. 22",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een deelnemer ziet dat zijn contactgegeven in de registratie onjuist is en vraagt om verbetering. Welk AVG-recht wordt hiermee uitgeoefend?",
    opties: [
      "Het recht om iedere verwerking automatisch te laten voortzetten.",
      "Het recht op rectificatie van onjuiste persoonsgegevens.",
      "Het recht om de gegevens van andere deelnemers te vergelijken.",
      "Het recht om de oorspronkelijke grondslag van een geaccrediteerde te kiezen.",
    ],
    sleutel: "B",
    toelichtingGoed: "De AVG kent betrokkenen het recht toe om onjuiste persoonsgegevens te laten rectificeren. Dit verzoek gaat precies over een fout contactgegeven.",
    toelichtingFout: "Een verzoek om een onjuist contactgegeven te verbeteren gaat niet over toegang tot gegevens van anderen of over het kiezen van een rechtsgrond.",
    gebruik: "meten",
    bronVerwijzing: "AVG: recht op rectificatie",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "scenario",
    stam: "Een deelnemer vraagt om verwijdering van zijn persoonsgegevens nadat hij de verwerking niet langer nodig acht. Welk uitgangspunt is juist?",
    opties: [
      "Een verwijderingsverzoek hoeft nooit inhoudelijk te worden beoordeeld.",
      "Alleen een geaccrediteerde kan om wissing vragen, omdat die een overeenkomst heeft.",
      "De deelnemer kan zich beroepen op het recht op wissing; de organisatie moet het verzoek volgens de AVG beoordelen.",
      "Een verzoek om wissing verandert automatisch elke andere betrokkene in een deelnemer.",
    ],
    sleutel: "C",
    toelichtingGoed: "Het recht op wissing geeft betrokkenen onder de AVG de mogelijkheid verwijdering van persoonsgegevens te vragen. Het verzoek moet inhoudelijk worden beoordeeld.",
    toelichtingFout: "Een betrokkene hoeft geen geaccrediteerde te zijn om een beroep op wissing te kunnen doen. Een organisatie kan zo'n verzoek niet zonder beoordeling negeren.",
    gebruik: "meten",
    bronVerwijzing: "AVG: recht op wissing",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "meerkeuze",
    stam: "Welke keuze illustreert het AVG-beginsel van dataminimalisatie het best bij het organiseren van een profielafname?",
    opties: [
      "Alle beschikbare personeelsgegevens verzamelen voor mogelijk toekomstig gebruik.",
      "Van iedere deelnemer dezelfde extra achtergrondinformatie vragen, ongeacht het doel.",
      "Persoonsgegevens verzamelen totdat de organisatie geen nieuwe velden meer kan bedenken.",
      "Alleen persoonsgegevens verzamelen die nodig zijn voor het vooraf bepaalde verwerkingsdoel.",
    ],
    sleutel: "D",
    toelichtingGoed: "Dataminimalisatie betekent dat persoonsgegevens toereikend, ter zake dienend en beperkt moeten zijn tot wat nodig is voor het verwerkingsdoel.",
    toelichtingFout: "Mogelijk toekomstig nut is geen reden om onbeperkt gegevens te verzamelen. Het uitgangspunt is beperking tot wat voor het doel nodig is.",
    gebruik: "meten",
    bronVerwijzing: "AVG: dataminimalisatie",
  },
  {
    instrumentId: CORPUS_INSTRUMENT,
    as: "weten",
    blok: "E",
    soort: "juistfout",
    stam: "Zowel de tabel voor deelnemer-afnames als die voor bekwaamheidsrondes bevat volgens het dossier een verwerkingsdoel en een versie van de privacyverklaring.",
    opties: null,
    sleutel: "juist",
    toelichtingGoed: "Het dossier vermeldt uitdrukkelijk dat beide tabellen verwerkingsdoel en privacyverklaring_versie dragen, naast hun onderscheiden standaardrechtsgrond.",
    toelichtingFout: "Dit is geen eigenschap van slechts één tabel. Het dossier beschrijft deze twee velden expliciet als aanwezig in beide relevante tabellen.",
    gebruik: "meten",
    bronVerwijzing: "ITEMBRON §4",
  },
];

/** Het aantal items per kennischeckblok in dit corpus. */
export function corpusdekking(): Record<string, number> {
  const telling: Record<string, number> = {};
  for (let i = 0; i < ITEMCORPUS_T4P.length; i += 1) {
    const blok = ITEMCORPUS_T4P[i].blok ?? "";
    telling[blok] = (telling[blok] ?? 0) + 1;
  }
  return telling;
}
